import type{ HealthData } from '@/@types/healthdata';
// 健康数据的示例数据
export const exampleHealthData: HealthData[] = [
  {
    id:1,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-10T10:00:00Z',
    height: 170,
    weight: 70,
    blood_glucose: 5.5,
    blood_triglyceride: 1.2,
    systolic_pressure: 120,
    diastolic_pressure: 80,
    heart_rate: 75,
    blood_cholesterol: 4.5,
    high_density_cholesterol: 1.5,
    low_density_cholesterol: 2.5,
    muscle_mass: 35,
    visceral_fat: 10,
    body_fat: 20,
    blood_oxygen_saturation: 98,
    body_temperature: 36.5,
    health_status: '优秀'
  },
  {
    id:2,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-11T10:00:00Z',
    height: 170,
    weight: 71,
    blood_glucose: 5.6,
    blood_triglyceride: 1.3,
    systolic_pressure: 122,
    diastolic_pressure: 82,
    heart_rate: 76,
    blood_cholesterol: 4.6,
    high_density_cholesterol: 1.6,
    low_density_cholesterol: 2.6,
    muscle_mass: 36,
    visceral_fat: 11,
    body_fat: 21,
    blood_oxygen_saturation: 97,
    body_temperature: 36.6,
    health_status: '良好'
  },
  {
    id:3,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-12T10:00:00Z',
    height: 170,
    weight: 72,
    blood_glucose: 5.7,
    blood_triglyceride: 1.4,
    systolic_pressure: 124,
    diastolic_pressure: 84,
    heart_rate: 77,
    blood_cholesterol: 4.7,
    high_density_cholesterol: 1.7,
    low_density_cholesterol: 2.7,
    muscle_mass: 37,
    visceral_fat: 12,
    body_fat: 22,
    blood_oxygen_saturation: 96,
    body_temperature: 36.7,
    health_status: '一般'
  },
  {
    id:4,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-13T10:00:00Z',
    height: 170,
    weight: 73,
    blood_glucose: 5.8,
    blood_triglyceride: 1.5,
    systolic_pressure: 126,
    diastolic_pressure: 86,
    heart_rate: 78,
    blood_cholesterol: 4.8,
    high_density_cholesterol: 1.8,
    low_density_cholesterol: 2.8,
    muscle_mass: 38,
    visceral_fat: 13,
    body_fat: 23,
    blood_oxygen_saturation: 95,
    body_temperature: 36.8,
    health_status: '加油'
  },
  {
    id:5,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-14T10:00:00Z',
    height: 170,
    weight: 74,
    blood_glucose: 5.9,
    blood_triglyceride: 1.6,
    systolic_pressure: 128,
    diastolic_pressure: 88,
    heart_rate: 79,
    blood_cholesterol: 4.9,
    high_density_cholesterol: 1.9,
    low_density_cholesterol: 2.9,
    muscle_mass: 39,
    visceral_fat: 14,
    body_fat: 24,
    blood_oxygen_saturation: 94,
    body_temperature: 36.9,
    health_status: '良好'
  },
  {
    id:6,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-15T10:00:00Z',
    height: 170,
    weight: 75,
    blood_glucose: 6.0,
    blood_triglyceride: 1.7,
    systolic_pressure: 130,
    diastolic_pressure: 90,
    heart_rate: 80,
    blood_cholesterol: 5.0,
    high_density_cholesterol: 2.0,
    low_density_cholesterol: 3.0,
    muscle_mass: 40,
    visceral_fat: 15,
    body_fat: 25,
    blood_oxygen_saturation: 93,
    body_temperature: 37.0,
    health_status: '优秀'
  },
  {
    id:7,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-16T10:00:00Z',
    height: 170,
    weight: 76,
    blood_glucose: 6.1,
    blood_triglyceride: 1.8,
    systolic_pressure: 132,
    diastolic_pressure: 92,
    heart_rate: 81,
    blood_cholesterol: 5.1,
    high_density_cholesterol: 2.1,
    low_density_cholesterol: 3.1,
    muscle_mass: 41,
    visceral_fat: 16,
    body_fat: 26,
    blood_oxygen_saturation: 92,
    body_temperature: 37.1,
    health_status: '一般'
  },
  {
    id:8,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-17T10:00:00Z',
    height: 170,
    weight: 77,
    blood_glucose: 6.2,
    blood_triglyceride: 1.9,
    systolic_pressure: 134,
    diastolic_pressure: 94,
    heart_rate: 82,
    blood_cholesterol: 5.2,
    high_density_cholesterol: 2.2,
    low_density_cholesterol: 3.2,
    muscle_mass: 42,
    visceral_fat: 17,
    body_fat: 27,
    blood_oxygen_saturation: 91,
    body_temperature: 37.2,
    health_status: '严重'
  },
  {
    id:9,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-18T10:00:00Z',
    height: 170,
    weight: 78,
    blood_glucose: 6.3,
    blood_triglyceride: 2.0,
    systolic_pressure: 136,
    diastolic_pressure: 96,
    heart_rate: 83,
    blood_cholesterol: 5.3,
    high_density_cholesterol: 2.3,
    low_density_cholesterol: 3.3,
    muscle_mass: 43,
    visceral_fat: 18,
    body_fat: 28,
    blood_oxygen_saturation: 90,
    body_temperature: 37.3,
    health_status: '良好'
  },
  {
    id:10,
    elderly_id: 1,
    elderly_name: '张三',
    measured_at: '2024-03-19T10:00:00Z',
    height: 170,
    weight: 79,
    blood_glucose: 6.4,
    blood_triglyceride: 2.1,
    systolic_pressure: 138,
    diastolic_pressure: 98,
    heart_rate: 84,
    blood_cholesterol: 5.4,
    high_density_cholesterol: 2.4,
    low_density_cholesterol: 3.4,
    muscle_mass: 44,
    visceral_fat: 19,
    body_fat: 29,
    blood_oxygen_saturation: 89,
    body_temperature: 37.4,
    health_status: '良好'
  }
];