/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressSelectorCom: typeof import('./components/AddressSelectorCom.vue')['default']
    CarouselCom: typeof import('./components/CarouselCom.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeaderCom: typeof import('./components/HeaderCom.vue')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpChatRound: typeof import('~icons/ep/chat-round')['default']
    IEpFirstAidKit: typeof import('~icons/ep/first-aid-kit')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMessageBox: typeof import('~icons/ep/message-box')['default']
    IEpReading: typeof import('~icons/ep/reading')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    LoadingCom: typeof import('./components/LoadingCom.vue')['default']
    PasswordConfirmation: typeof import('./components/PasswordConfirmation.vue')['default']
    RealNameAuthCom: typeof import('./components/RealNameAuthCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCom: typeof import('./components/SearchCom.vue')['default']
    SetCom: typeof import('./components/SetCom.vue')['default']
    SidebarCom: typeof import('./components/SidebarCom.vue')['default']
    ThreeCom: typeof import('./components/ThreeCom.vue')['default']
    UserInfoCom: typeof import('./components/UserInfoCom.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
